"""edit relationships rename comments rating

Revision ID: 5e551e8f99d2
Revises: df94157ac48b
Create Date: 2025-02-22 11:47:25.675696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e551e8f99d2'
down_revision: Union[str, None] = 'df94157ac48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('capacity', sa.Integer(), nullable=False))
    op.drop_column('comments', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('comments', 'capacity')
    # ### end Alembic commands ###
