"""delete media-id from comments table

Revision ID: 62ca6852dcd2
Revises: 6b10b5623e22
Create Date: 2025-02-17 16:19:30.959794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62ca6852dcd2'
down_revision: Union[str, None] = '6b10b5623e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_column('comments', 'media_id')
    op.alter_column('media_contents', 'media_type',
               existing_type=mysql.ENUM('PHOTO', 'VIDEO'),
               type_=sa.Enum('IMAGE', 'VIDEO', name='mediatypes'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_contents', 'media_type',
               existing_type=sa.Enum('IMAGE', 'VIDEO', name='mediatypes'),
               type_=mysql.ENUM('PHOTO', 'VIDEO'),
               existing_nullable=False)
    op.add_column('comments', sa.Column('media_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_2', 'comments', 'media_contents', ['media_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
