"""file_hash stops being unique

Revision ID: 72a6024af995
Revises: 5e551e8f99d2
Create Date: 2025-02-22 12:48:48.290711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a6024af995'
down_revision: Union[str, None] = '5e551e8f99d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('file_hash', table_name='media_contents')
    op.drop_index('file_hash_2', table_name='media_contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('file_hash_2', 'media_contents', ['file_hash'], unique=True)
    op.create_index('file_hash', 'media_contents', ['file_hash'], unique=True)
    # ### end Alembic commands ###
