"""edit models fields

Revision ID: df94157ac48b
Revises: 62ca6852dcd2
Create Date: 2025-02-17 20:19:00.054925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df94157ac48b'
down_revision: Union[str, None] = '62ca6852dcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_contents', 'file_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.create_unique_constraint(None, 'media_contents', ['file_hash'])
    op.alter_column('posts', 'create_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.drop_index('comments_id', table_name='posts')
    op.drop_index('media_id', table_name='posts')
    op.drop_index('source_id', table_name='posts')
    op.drop_column('posts', 'comments_id')
    op.drop_column('posts', 'source_id')
    op.drop_column('posts', 'media_id')
    op.add_column('sources', sa.Column('posting_at', sa.DATETIME(), nullable=False))
    op.drop_column('sources', 'posting_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('posting_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.drop_column('sources', 'posting_at')
    op.add_column('posts', sa.Column('media_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('comments_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('source_id', 'posts', ['source_id'], unique=True)
    op.create_index('media_id', 'posts', ['media_id'], unique=True)
    op.create_index('comments_id', 'posts', ['comments_id'], unique=True)
    op.alter_column('posts', 'create_at',
               existing_type=sa.DATETIME(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'media_contents', type_='unique')
    op.alter_column('media_contents', 'file_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
